### ISSUE TITLE
Adding content to Bibliography

### ISSUE THREAD

**Issue by jaskaran1** [ucsd-thesis/ucsd-thesis#10]
I was trying to add references in bibliography but it doesn't update. I am using overleaf to edit my thesis.

The comment in the template.tex file says that template.bbl file needs to be separately recompiled as a template.bbl file.

How is this supposed to be done?

**Comment by coresn** [comment]
Overleaf incorporates bibtex automatically, so there's no need for an independent compile. It uses the .bib file directly, so edit that (in other systems it is typically used to generate the .bbl file, which you can delete).

**Comment by jaskaran1** [comment]
Thanks. Just attaching a [video link](https://www.overleaf.com/help/97-how-to-include-a-bibliography-using-bibtex#.WjXXk7Q-cdU) here explaining the process of including bibliography using bibtex.
