### ISSUE TITLE
Section title breaking with hyphen

### ISSUE THREAD

**Issue by codyallen08** [ucsd-thesis/ucsd-thesis#19]
Not really a bug, but I had many section titles that would hyphenate, however, the actual hyphen did not respect the page margins and the Graduate Dissertation reviewer caught this.  A simple fix was to include:
\usepackage[raggedright]{titlesec} % do not break section title words

in the preamble.  I wanted to at least mention this as it took some time to find this solution.  Thanks.

**Comment by bcipolli** [comment]
@cwallen08ucsd awesome, thanks for sharing! Any chance you want to submit a pull request? I'd be happy to review/merge!

**Comment by codyallen08** [comment]
I think I did the pull request correctly; please let me know if you need me to change anything.  Thanks!

**Comment by bcipolli** [comment]
@cwallen08ucsd sorry for the delay. was trying to validate this, got pulled away.

Will try this again today!

**Comment by bcipolli** [comment]
Verified that it doesn't break anything - and that's enough for me today :) Huzzah, thanks @cwallen08ucsd !

**Comment by codyallen08** [comment]
Awesome, thanks Ben!  Take care out there!
