### ISSUE TITLE
New Format starting Fall 2017?

### ISSUE THREAD

**Issue by bkurtz** [ucsd-thesis/ucsd-thesis#5]
Haven't heard a lot of details about this, but I heard it mentioned today that there's a new format that Grad Division wants going forward (something about all page numbers now being bottom-centered).  Apparently the new format is not required yet (and AFAICT, the formatting guide has yet to be updated), but this will be something to be aware of going forward.

**Comment by devinplatt** [comment]
According to https://grad.ucsd.edu/progress/dissertation-thesis.html,
"New margin and pagination requirements are in effect beginning Fall 2017"
however
"Dissertations/theses already formatted according to the 2016-2017 manual will be accepted only through Fall 2017 (final appointment must be completed by December 15, 2017"

So if you're using the old formatting you're OK if you have your final appointment by December 15, 2017. Regardless, this repository should get updated.

The new requirements can be found at:
https://grad.ucsd.edu/_files/academic-affairs/Dissertations_Theses_Formatting_Manual_17-18.pdf

**Comment by bcipolli** [comment]
The pagination change (centering) was just merged (yay!). Any other needs here?

**Comment by bkurtz** [comment]
TBH, I submitted already, so I qualified for the old formatting rules and don't have any familiarity with the new rules.  Hopefully @devinplatt or someone else can chime in.

**Comment by jnussbac** [comment]
I added the pagination change, will put in the margin changes today :)

**Comment by jaskaran1** [comment]
#8 
Hi, 
It seems like the latex is broken when imported to sharelatex or overleaf. Can somebody help here?
I have reference the issue above.
Thanks.

**Comment by bcipolli** [comment]
@jnussbac any chance you can push up a PR with the margin changes and get us to zero open issues? :)

**Comment by coresn** [comment]
The needed modifications are in ucsd.cls lines 1579 (plain should be thesis) and a close bracket in line 1585.

**Comment by bcipolli** [comment]
done
