### ISSUE TITLE
Issue Importing to Overleaf

### ISSUE THREAD

**Issue by jotruebl** [ucsd-thesis/ucsd-thesis#8]
I'm somewhat new to Latex and trying to use overleaf with this template. However, I get the following error right after "\documentclass[12pt,chapterheads]{ucsd}" is called.

Runaway definition?
->\let \@mkboth \markboth \def \@oddfoot {\hbox {}\hfil \rmfamily \thepage \ETC
.
File ended while scanning definition of \ps@plain.
<inserted text> 
                }
l.94 

 No idea what it means. Can anyone help me out?

**Comment by jaskaran1** [comment]
I am getting the same error when I export it to sharelatex. No idea how to solve this.

**Comment by devinplatt** [comment]
It appears that this error first appears with commit https://github.com/ucsd-thesis/ucsd-thesis/commit/8ca92eba82aa33730e018da7f79f51498c43c6cf

(verified this by uploading code to Overleaf from this commit and the previous commit)

**Comment by devinplatt** [comment]
There's a missing bracket (}), and the thesis page style is accidentally defined as "plain". Correcting both makes Overleaf work.

**Comment by devinplatt** [comment]
See https://github.com/ucsd-thesis/ucsd-thesis/pull/9

**Comment by jaskaran1** [comment]
Thanks @devinplatt .

**Comment by bcipolli** [comment]
Closed via #9 . Please verify & reopen if necessary, thx!
